### Make an array in numpy

In [1]:
import numpy as np

v = np.array([5, 2, 1])

print(v)

[5 2 1]


In [2]:
print(v[1])
print(v.shape)

2
(3,)


In [3]:
v_t = np.transpose(v)
print(v_t)
v_t.shape

[5 2 1]


(3,)

In [4]:
v = np.array([[5, 2, 1]])
print(v)
print(v[0][1])
print(v.shape)

[[5 2 1]]
2
(1, 3)


In [5]:
v_t = np.transpose(v)
print(v_t.shape)
print(v_t)

(3, 1)
[[5]
 [2]
 [1]]


### Make a matrix in numpy

In [6]:
v = np.array([[1, 2, 3], [2, 0, 1]])
print(v.shape)
print(v.size)

(2, 3)
6


In [7]:
v_t = np.transpose(v)
print(v_t.shape)

(3, 2)


#### Arrange or reshape the matrix

In [8]:
v = np.array([[1, 2, 3], [2, 0, 1]])
print(v.reshape(6, 1))
print('---')
print(v.reshape(3, 2))

[[1]
 [2]
 [3]
 [2]
 [0]
 [1]]
---
[[1 2]
 [3 2]
 [0 1]]


In [9]:
print(v.reshape(3, 1, 2))
print('---')
print(v.reshape(3, 1, -1))

[[[1 2]]

 [[3 2]]

 [[0 1]]]
---
[[[1 2]]

 [[3 2]]

 [[0 1]]]


### Make a 3D Tensor

In [10]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)
print('------------------')
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
------------------
(2, 2, 3)


In [11]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
print(v.size)

12


In [13]:
print(v.reshape(3, 2, -1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [14]:
a = v.reshape(3, -1)
print(a.shape)

(3, 4)


### 4D Tensors

In [15]:
v = np.zeros((2, 3, 5, 5))
print(v)
print(v.shape)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
(2, 3, 5, 5)


In [17]:
v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v.shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 

### Array multiplication
Multiply the rows of the first array with the columns of the second.

In [19]:
a = np.array([[4, 2, 3], [2, 0, 1]])
b = np.transpose(a)

In [27]:
c = np.dot(a, b)
print(c)

[[29 11]
 [11  5]]


In [28]:
c = np.dot(b, a)
print(c)

[[20  8 14]
 [ 8  4  6]
 [14  6 10]]


### Pseudo inverse of non-squared matrix

In [32]:
pinv_a = np.linalg.pinv(a)

print(pinv_a)
print('------------------')
print(np.dot(a, pinv_a))
print('------------------')
print(np.dot(pinv_a, a))

[[-0.08333333  0.58333333]
 [ 0.41666667 -0.91666667]
 [ 0.16666667 -0.16666667]]
------------------
[[ 1.00000000e+00  7.77156117e-16]
 [-2.77555756e-17  1.00000000e+00]]
------------------
[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


#### In numpy we have np.dot for matrix multiplication

#### For elementwise multiplication we can use:

In [34]:
a = np.array([[4, 3], [2, 1]])
b = np.array([[5, 1], [6, 3]])

np.multiply(a, b)

array([[20,  3],
       [12,  3]])